In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import random
from IPython.display import display, clear_output
from time import sleep

import numpy as np
import time
import sys
from functools import reduce

from utils import show_field, Board
from agents.random import RandomAgent

In [12]:
x = np.zeros((5, 3))
x[:,1] = 1
x

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [15]:
np.concatenate(([1], [2, 3]))

array([1, 2, 3])

In [16]:
x = torch.randn((3))
torch.topk(x, 2).indices

tensor([2, 1])